server:
  port: 8081

spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentDB
    username: usr
    password: pwd
    hikari:
      schema: auth
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:paymentDB
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE