server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/paymentDB
    username: usr
    password: pwd
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/paymentDB
    user: usr
    password: pwd
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:paymentDB
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver

app:
  ext-service-url: http://localhost:8080/

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE